### ISSUE TITLE
x509-exporter exclude-list from watch-folder

### ISSUE THREAD

**Issue by rdegez** [enix/helm-charts#21]
On k8s cluster upgrade, when kubeadm rotate certificates, it keeps expired ones in /etc/kubernetes/pki/expired.

So the x509-exporter, having /etc/kubernetes/pki configured as watch-folder, will keep raising alarms on expired certificates in /etc/kubernetes/pki/expired.

Maybe we can add some way to exclude or ignore certains folders in the configured watchfolder.

**Comment by npdgm** [comment]
Thanks!
This was fixed upstream in x509-exporter. Watching directories won't walk the tree anymore and scan files on the first level.
We'll add more options to the chart when x509-exporter implements both behaviours.
