### ISSUE TITLE
Provide sample prometheus alert rules in documentation

### ISSUE THREAD

**Issue by rdegez** [enix/helm-charts#37]
See $subject :-)

Pretty sure one might find it useful.

**Comment by rwin-novo** [comment]
Indeed. I have no idea what the Prometheus Operator is and would stick to the "plain" rules, at least for now.

**Comment by abuisine** [comment]
on which project ?

**Comment by rwin-novo** [comment]
I personally was meaning x509-exporter as this is the project which attracted me here. Dunno about OP.

**Comment by npdgm** [comment]
Prometheus rules being managed by a chart template, they should not be replicated in it's documentation in raw form.
However I have added them to the documentation for the main project: enix/x509-certificate-exporter@5ab89725a1fdaafbb839076fe6b57b7a9733e2f5
Cheers
