### ISSUE TITLE
[x509-exporter] hostPathsExporter not using defined resources

### ISSUE THREAD

**Issue by Thorndike** [enix/helm-charts#63]
name: x509-certificate-exporter
version: 1.14.1

The value.yaml does include a resources definition for hostPathsExporter daemonsets but those values are not reflected in the resulting pods.
Am I missing something in the configuration?

**Comment by npdgm** [comment]
Hello @Thorndike,
You are absolutely correct, this looks to be a regression from when the chart was revamped months ago.
Thanks for reporting the issue.
I'm testing a patch and will notify you when 1.15.0 is released.
Cheers

**Comment by npdgm** [comment]
@Thorndike, version 1.15.0 was released with a fix for missing DaemonSet resources definition.
Nice catch, thanks for helping is improve this Chart.
Cheers
