### ISSUE TITLE
extensions/v1beta1 deprecated

### ISSUE THREAD

**Issue by chribo** [enix/helm-charts#70]
Replacing extensions/v1beta1 with networking.k8s.io/v1
`
diff -r netbox/templates/ingress.yaml netbox.orig/templates/ingress.yaml
4c4
< apiVersion: networking.k8s.io/v1
---
> apiVersion: extensions/v1beta1
37d36
<             pathType: ImplementationSpecific
39,42c38,39
<               service:
<                 name: {{ $fullName }}
<                 port:
<                   name: http
---
>               serviceName: {{ $fullName }}
>               servicePort: http

`
patch attached (thanks to stupid filter: ingress.txt instead of ingress.patch
[ingress.txt](https://github.com/enix/helm-charts/files/7607925/ingress.txt)
)

**Comment by npdgm** [comment]
Hello @chribo, @rlex,
Thanks for reporting this issue. Unfortunately the Netbox chart from our repository has been deprecated and cannot be maintained anymore.
Please refer to #50 if you have remarks on the migration to https://github.com/bootc/netbox-chart
Cheers
